import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Session, getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./components/LogoutBtn";
import LoginBtn from "./components/LoginBtn";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let session: Session | null = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`bg-customBg min-h-screen flex flex-col ${inter.className}`}
      >
        <Navbar session={session} />
        {children}
      </body>
    </html>
  );
}
