import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Session, getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import LoginBtn from "./LoginBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let session: Session | null = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`bg-customBg min-h-screen flex flex-col ${inter.className}`}
      >
        <div className="bg-white flex items-center justify-between p-4 border-1 border-solid border-customGray">
          <div className="flex">
            <Link href="/" className="logo">
              <img className="w-36" src="/logo_transparent.svg" />
            </Link>

            <ul className="flex">
              <li className="mx-4">about</li>
              <li>list</li>
            </ul>
          </div>

          {session ? (
            <span>
              {session.user?.name}
              <LogoutBtn />
            </span>
          ) : (
            <LoginBtn />
          )}

          {children}
        </div>
      </body>
    </html>
  );
}
